<?php
/**
 * Created by Administrator.
 * Date: 2018/5/28 21:55
 * github: https://github.com/lbmzorx
 */

namespace frontend\controllers;

use common\components\helper\SignHelper;
use common\models\admindata\Admin;
use yii\web\Controller;
use yii\web\Response;

class SystemController extends Controller
{
    public $enableCsrfValidation=false;
    public function beforeAction($action)
    {
        \yii::$app->response->format=Response::FORMAT_JSON;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionClearCache(){
        $request=\yii::$app->request;
        $admin=Admin::findOne(['auth_key'=>$request->getBodyParam('accessKey')]);
        if($admin){
            $sign=SignHelper::signAll($request->getBodyParams(),$admin->secretKey,$admin->auth_key,true,true);
            if($sign && $sign['sign']==$request->getBodyParam('sign')){

            }

        }


    }
}