<?php
/**
 * Created by Administrator.
 * Date: 2018/6/9 21:20
 * github: https://github.com/lbmzorx
 */

namespace frontend\controllers;


use backend\models\Article;
use common\models\startdata\UserInfo;
use frontend\models\FansForm;
use lbmzorx\components\action\AjaxFormAction;
use yii\base\Controller;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class UserController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index','attention','chat','message'],
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' =>  ['index','attention','chat','message'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'index'   => ['GET'],
                    'chat' => ['GET', 'PUT', 'POST'],
                    'attention' => ['GET','PUT', 'POST'],
                    'collection' => ['PUT', 'POST'],
                    'message'=>['GET'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'attention'=>[
                'class'=>AjaxFormAction::className(),
                'modelClass'=>FansForm::className(),
                'verifyMethod'=>'fans',
                'successMsg'=>function($model,$action){
                    if($model->getAttentionType()){
                        return \yii::t('app','Following Success!');
                    }else{
                        return \yii::t('app','Unfollow  Success!');
                    }
                },
                'isErrorMsg'=>true,
                'errorMsg'=>\yii::t('app','Following Failed!'),
            ],
        ]; // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        $user=\yii::$app->request->get('id')?:\yii::$app->user->id;

        $query=Article::find()->where([
            'status'=>Article::STATUS_AUDIT_PASSED,
            'publish'=>Article::PUBLISH_PUBLISHED,
            'auth'=>Article::AUTH_ALL_USERS,
            'user_id'=>$user,
        ])->andFilterWhere([
            'tag'=>\yii::$app->request->get('tag'),
            'article_cate_id'=>\yii::$app->request->get('cate_id'),
        ])->with('user');
        $provider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => [
                'pageSize' => 20,
                'pageParam'=>'page',
                'pageSizeParam'=>'per-page',
            ],
            'sort' => [
                'defaultOrder' => [
                    'sort' => SORT_DESC,
                    'id' => SORT_DESC,
                ]
            ],
        ]);
        return $this->render('index',['provider'=>$provider]);
    }


    public function actionMessage(){
        return $this->render('message');
    }

    public function actionMessageDetail(){
        return $this->render('message-detail');
    }
}