<?php
namespace common\models\startdata;

use Yii;
use common\models\startdatabase\Contact as BaseModelContact;
use yii\behaviors\AttributesBehavior;
use yii\caching\TagDependency;
use yii\db\ActiveRecord;

/**
* This is the data class for [[common\models\startdatabase\Contact]].
* Data model definde model behavior and status code.
* @see \common\models\startdatabase\Contact
*/
class Contact extends BaseModelContact
{
    /**
     * The cache tag
     */
    const CACHE_TAG='common_models_startdata_Contact';


    const STATUS_UNREAD=0;
    const STATUS_READ=1;
    /**
    * 状态
    * 状态.tran:0=未读,1=已读.code:0=Unread,1=Read.
    * @var array $status_code
    */
    public static $status_code = [0=>'Unread',1=>'Read',];

    /**
     * get status code attribute list
     */
    public static function statusCodes(){
        return [
            'status'
        ];
    }

    /**
    * @inheritdoc
    */
    public function rules()
    {
        return array_merge(parent::rules(),[
            [['status'], 'in', 'range' => [0,1,]],
            [['status'], 'default', 'value' =>0,],
        ]);
    }

    /**
    * @inheritdoc
    */
    public function scenarios()
    {
        return [
            'default' => [
                'id',
                'name',
                'email',
                'subject',
                'body',
                'ip',
                'status',
                'add_time',
            ],
            'search' => [
                'id',
                'name',
                'email',
                'subject',
                'body',
                'ip',
                'status',
                'add_time',
            ],
            'view' => [
                'id',
                'name',
                'email',
                'subject',
                'body',
                'ip',
                'status',
                'add_time',
            ],
            'update' => [
                'name',
                'email',
                'subject',
                'body',
                'ip',
                'status',
            ],
            'create' => [
                'name',
                'email',
                'subject',
                'body',
                'ip',
                'status',
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'timeUpdate'=>[
                'class' => \yii\behaviors\TimestampBehavior::className(),
                'attributes' => [
                    self::EVENT_BEFORE_INSERT => ['add_time'],
                ],
            ],
            'getStatusCode'=>[
                'class' => \lbmzorx\components\behavior\StatusCode::className(),
                'category' =>'statuscode',
            ],
            'insert_value'=>[
                'class'=>AttributesBehavior::className(),
                'attributes'=>[
                    'ip'=>[
                        ActiveRecord::EVENT_BEFORE_INSERT=>\yii::$app->request->getUserIP(),
                    ],
                    'status'=>[
                        ActiveRecord::EVENT_BEFORE_INSERT=>self::STATUS_UNREAD,
                    ],
                ],
            ],
        ];
    }

    /**
     * If is tree which have parent_id
     * @return boolean
     */
    public static function isTree(){
        return false;
    }


    public function afterSave($insert , $changedAttributes)
    {
        TagDependency::invalidate(\yii::$app->cache,self::CACHE_TAG);
        parent::afterSave($insert , $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        TagDependency::invalidate(\yii::$app->cache,self::CACHE_TAG);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

}
