<?php
namespace common\models\startdata;

use Yii;
use common\models\startdatabase\UserInfo as BaseModelUserInfo;
use yii\caching\TagDependency;

/**
* This is the data class for [[common\models\startdatabase\UserInfo]].
* Data model definde model behavior and status code.
* @see \common\models\startdatabase\UserInfo
*/
class UserInfo extends BaseModelUserInfo
{
    /**
     * The cache tag
     */
    const CACHE_TAG='common_models_startdata_UserInfo';


    /**
     * get status code attribute list
     */
    public static function statusCodes(){
        return [
        ];
    }

    /**
    * @inheritdoc
    */
    public function rules()
    {
        return array_merge(parent::rules(),[
            [['fans','attention','article'], 'default', 'value' =>0,],
        ]);
    }

    /**
    * @inheritdoc
    */
    public function scenarios()
    {
        return [
            'default' => [
                'id',
                'user_id',
                'fans',
                'attention',
                'article',
            ],
            'search' => [
                'id',
                'user_id',
                'fans',
                'attention',
                'article',
            ],
            'view' => [
                'id',
                'user_id',
                'fans',
                'attention',
                'article',
            ],
            'update' => [
                'user_id',
                'fans',
                'attention',
                'article',
            ],
            'create' => [
                'user_id',
                'fans',
                'attention',
                'article',
            ],
        ];
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser(){
        return $this->hasOne(User::className(),['id'=>'user_id']);
    }

    /**
     * get relation columns
     * @return array
     */
    public static function columnRetions(){
        return [
            'user_id'=>'User',
        ];
    }

    /**
     * If is tree which have parent_id
     * @return boolean
     */
    public static function isTree(){
        return false;
    }


    public function afterSave($insert , $changedAttributes)
    {
        TagDependency::invalidate(\yii::$app->cache,self::CACHE_TAG);
        parent::afterSave($insert , $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        TagDependency::invalidate(\yii::$app->cache,self::CACHE_TAG);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

}
