<?php
/**
 * Created by Administrator.
 * Date: 2018/5/24 0:09
 * github: https://github.com/lbmzorx
 */

namespace backend\models;


class Article extends \common\models\startdata\Article
{
    public function beforeSave($insert)
    {
        $this->admin_id=\yii::$app->user->id;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}