<?php
/**
 * Created by Administrator.
 * Date: 2018/6/13 20:14
 * github: https://github.com/lbmzorx
 */
namespace backend\models;


use common\models\startdata\User;
use yii\base\Model;

class Message extends Model
{
    public $message_type='';
    public $priority;
    public $group_type;
    public $content;
    public $to_id;

    public function rules()
    {
        return [
            [['message_type','priority','group_type',],'integer',],
            ['content','string','max'=>254],
            ['to_id','exist','targetClass'=>User::className(),],

        ]; // TODO: Change the autogenerated stub
    }
}