<?php
/**
 * Created by Administrator.
 * Date: 2018/6/17 15:09
 * github: https://github.com/lbmzorx
 */

namespace backend\models;

use common\models\admin\Admin;
use Yii;
use lbmzorx\components\behavior\RsaAttribute;
use yii\base\Model;
class ResetPasswordForm extends Model
{
    public $oldPassword;
    public $newPassword;
    public $confirmPassword;
    public $verifyCode;

    public function rules()
    {
        return [
            [['oldPassword','newPassword','confirmPassword'],'required'],
            [['oldPassword','newPassword','confirmPassword'],'string','min'=>6,'max'=>25],
            [ 'newPassword','match','pattern'=>'/^(?![0-9]+$)(?![a-zA-Z]+$)[0-9A-Za-z]{8,25}$/','message'=>\yii::t('app','Password must include number,lowercase letters,and uppercase letters')],
            ['verifyCode','captcha'],
        ]; // TODO: Change the autogenerated stub
    }


    public function behaviors()
    {
        return [
            'bs_rsa'=>[
                'class'=>RsaAttribute::className(),
                'rsaAtAttributes'=>['oldPassword','newPassword','confirmPassword'],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'oldPassword' => Yii::t('app', 'Old Password'),
            'newPassword' => Yii::t('app', 'New Password'),
            'confirmPassword' => Yii::t('app', 'Confirm Password'),
            'verifyCode'=>\yii::t('app','Verify Code'),
        ];
    }

    public function resetPassword(){
        $admin=$this->getAdmin();
        $admin->setPassword($this->newPassword);
        return $admin->save();
    }

    public function getAdmin(){
        return Admin::findOne(['id'=>\yii::$app->user->id]);
    }
}