<?php
/**
 * Created by Administrator.
 * Date: 2018/8/11 12:46
 * github: https://github.com/lbmzorx
 */

namespace console\controllers;

use Yii;
use yii\console\Controller;
use yii\httpclient\Client;
use yii\log\Logger;

class YiiChinaController extends Controller
{

    protected $ch;
    protected $cookie_file;
    protected $user_agent;

    protected $httpClient;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->ch=curl_init();
        $this->cookie_file=\Yii::getAlias('@runtime/yiiChina').'/cookie_login.txt';
        $this->user_agent="Mozilla/5.".rand(0,100)." (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0";
        \yii::$app->getLog()->logger->log('User Agent:'.$this->user_agent,Logger::LEVEL_INFO,'Auto login');
    }

    public function actionAutoLogin(){
        if( $res=$this->registation() == false ){
            if ( $this->login() ){
                if( $res=$this->registation()){
                    echo 'Register Success';
                    \yii::$app->getLog()->logger->log('Register Success',Logger::LEVEL_WARNING,'Auto login');
                }else{
                    echo 'after login'.$res;
                }
            }
        }else{
            echo 'success register true login'.$res;
            \yii::$app->getLog()->logger->log('Register Success',Logger::LEVEL_WARNING,'Auto login');
        }

        curl_close ($this->ch);
    }

    /**
     * 签到
     */
    protected function registation(){
        $url='https://www.yiichina.com/';
        $res=$this->httpGet($url);
        if(preg_match('/<meta name="csrf-token" content="(.*)">/',$res,$match)){
            if(isset($match[1])){
                $data=[
                    '_csrf'=>$match[1],
                ];
                $url='https://www.yiichina.com/registration';
                $res=$this->httppost($url,$data);
                $res=json_decode($res,JSON_OBJECT_AS_ARRAY);
                if(isset($res['status']) && $res['status']=='-1'){
                    echo "Register not login\n";
                    \yii::$app->getLog()->logger->log('Register not login',Logger::LEVEL_INFO,'Auto login');
                    return false;
                }else{
                    echo "Register Success\n";
                    \yii::$app->getLog()->logger->log('Register Success',Logger::LEVEL_INFO,'Auto login');
                    return true;
                }
            }else{
                echo 'Register not match csrf string ';
                \yii::$app->getLog()->logger->log('Register match csrf string cant get csrf string',Logger::LEVEL_INFO,'Auto login');
            }
        }else{
            echo 'Register not match csrf string ';
            \yii::$app->getLog()->logger->log('Register not match csrf string ',Logger::LEVEL_INFO,'Auto login');
        }
        return false;
    }

    protected function login(){
        $url='https://www.yiichina.com/login';
        $res=$this->httpGet($url);
        if(preg_match('/<meta name="csrf-token" content="(.*)">/',$res,$match)){
            if(isset($match[1])){
                $data=[
                    '_csrf'=>$match[1],
                    'LoginForm[username]'=>'123',
                    'LoginForm[password]'=>'123',
                    'LoginForm[rememberMe]'=>1,
                    'login-button'=>'',
                ];
                $res=$this->httppost($url,$data);

                if(preg_match('/HTTP\/1\.1\s302\sFound[.\s\S]*Location: https:\/\/www\.yiichina\.com\//',$res)){
                    echo "Login YiiChina Success!";
                    \yii::$app->getLog()->logger->log('Login YiiChina Success!',Logger::LEVEL_INFO,'Auto login');
                    return true;
                }else{
                    \yii::$app->getLog()->logger->log('Login YiiChina in exception!',Logger::LEVEL_INFO,'Auto login');
                }
            }else{
                \yii::$app->getLog()->logger->log('Can match csrf string in login Page ,but can\'t get csrf string! ',Logger::LEVEL_INFO,'Auto login');
                echo "Cant't match csrf string in login Page  \n";
            }
        }else{
            echo "Cant't match csrf string in login Page  \n";
            \yii::$app->getLog()->logger->log('Cant\'t match csrf string in login Page ',Logger::LEVEL_INFO,'Auto login');
        }
        return false;
    }


    protected function httpGet($url){
        curl_setopt ( $this->ch, CURLOPT_HTTPGET, 1 );
        curl_setopt ( $this->ch, CURLOPT_URL, $url );
        curl_setopt($this->ch, CURLOPT_SSL_VERIFYHOST, 2);
        curl_setopt($this->ch, CURLOPT_HEADER, 1);
        curl_setopt ($this->ch, CURLOPT_USERAGENT, $this->user_agent);
        curl_setopt($this->ch, CURLOPT_COOKIEJAR,  $this->cookie_file); //存储cookies
        curl_setopt_array($this->ch,[
            'Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8',
        ]);
        if(strlen($url) > 5 && strtolower(substr($url,0,5)) == "https" ) {
            curl_setopt($this->ch, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($this->ch, CURLOPT_SSL_VERIFYHOST, false);
        }
        curl_setopt($this->ch, CURLOPT_RETURNTRANSFER, 1);
        return curl_exec ( $this->ch );
    }

    protected function httppost($url,$data){
        curl_setopt ( $this->ch, CURLOPT_POST, 1 );
        curl_setopt ( $this->ch, CURLOPT_POSTFIELDS,$data);
        curl_setopt ( $this->ch, CURLOPT_URL, $url );
        curl_setopt ($this->ch, CURLOPT_COOKIE, $this->cookie_file);
        curl_setopt($this->ch, CURLOPT_SSL_VERIFYHOST, 2);
        curl_setopt($this->ch, CURLOPT_RETURNTRANSFER, 1);
        //https 请求
        if(strlen($url) > 5 && strtolower(substr($url,0,5)) == "https" ) {
            curl_setopt($this->ch, CURLOPT_SSL_VERIFYPEER, false);
            curl_setopt($this->ch, CURLOPT_SSL_VERIFYHOST, false);
        }
        return curl_exec ( $this->ch );
    }

}