<?php
namespace frontend\widget;

use common\models\startdata\ArticleCommit;
use lbmzorx\components\helper\TreeHelper;
use Yii;
use common\models\startdata\ArticleCate;
use yii\caching\TagDependency;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

/**
 * Created by Administrator.
 * Date: 2018/5/20 14:38
 * github: https://github.com/lbmzorx
 */
class ArticleCommitWidget extends PanelWidget
{
    public $condition=[];
    public $ulOption=[];
    public $liOption=[];
    public $articleCommit;
    public $article_id;
    public $commitCount;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($this->ulOption['class'])){
            $this->ulOption['class']='list-group';
        }
        if(empty($this->liOption['class'])){
            $this->liOption['class']='list-group-item';
        }
    }

    public function getHeadContent()
    {
        return Html::tag('h4',Yii::t('app','Commits').'   '.Html::tag('span',$this->commitCount,[]).\yii::t('app','Rows'));//Html::tag('h3',Yii::t('app','Category'),['class'=>'panel-title']); // TODO: Change the autogenerated stub
    }

    public function getBodyContent()
    {
        $form;
    }

}