<?php
namespace frontend\widget;

use common\models\startdata\User;
use common\models\startdata\UserInfo;
use Yii;
use common\models\startdata\ArticleCate;
use yii\caching\TagDependency;
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * Created by Administrator.
 * Date: 2018/5/20 14:38
 * github: https://github.com/lbmzorx
 */
class UserCardWidget extends PanelWidget
{
    public $condition=[];
    public $ulOption=[];
    public $liOption=[];
    public $userId;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        if(empty($this->ulOption['class'])){
            $this->ulOption['class']='list-group';
        }
        if(empty($this->liOption['class'])){
            $this->liOption['class']='list-group-item';
        }
    }

    public function getHeadContent()
    {
        return '';//Html::tag('h3',Yii::t('app','Category'),['class'=>'panel-title']); // TODO: Change the autogenerated stub
    }

    public function getBodyContent()
    {
        $data=$this->getUserInfo($this->condition);


        $head=Html::tag('div',
            Html::a(
                Html::tag('div',Html::img($data['head_img'],['alt'=>$data['username']]),['class'=>'media-left mr-2']).
                Html::tag('div',$data['username'],['class'=>'media-body']),['/user','id'=>$this->userId],[])
            ,['class'=>'media']);

        $userinfo=
        Html::tag('div',\yii::t('app','Followers').Html::tag('em',isset($data['userInfo']['fans'])?$data['userInfo']['fans']:'0'),['class'=>'userInfo']).
        Html::tag('div',\yii::t('app','Followings').Html::tag('em',isset($data['userInfo']['attention'])?$data['userInfo']['attention']:0),['class'=>'userInfo']).
        Html::tag('div',\yii::t('app','Articles').Html::tag('em',isset($data['userInfo']['article'])?$data['userInfo']['article']:0),['class'=>'userInfo']);

        $status=Html::tag('div',$userinfo,['class'=>'user-status']);

        $footerContent='';
        if($this->userId==\yii::$app->user->id){
            $footerContent=Html::tag(Html::a(Html::tag('i',['class'=>'fa fa-plus']).\yii::t('app','Follow'),'javascript:void(0)',
                [
                    'class'=>'btn btn-sm btn-primary',
                    'id' =>'follow-this-user',
                    'data-user'=>$data['username'],
                ])).
                Html::tag(Html::a(Html::tag('i',['class'=>'fa fa-plus']).\yii::t('app','Chat'),'javascript:void(0)',
                    [
                        'class'=>'btn btn-sm btn-primary',
                        'id' =>'chat-this-user',
                        'data-user'=>$data['username'],
                    ]));
        }
        $footer=Html::tag('div',$footerContent,['class'=>'user-footer']);

        $frame=Html::tag('div',Html::tag('div',$head.$status.$footer,['class'=>'card-body']),['class'=>'card']);
        return Html::tag('div',$frame,$this->ulOption); // TODO: Change the autogenerated stub
    }


    public function getUserInfo($condition){
        if($this->userId){
            $cache=\yii::$app->cache;
            $key=serialize(['type'=>'user_info',__METHOD__]);
            if($data=$cache->get($key)){
                return $data;
            }else{
                $data=User::find()->select('username,head_img')->where([
                        'status'=>User::STATUS_ACTIVE,
                        'id'=>$this->userId,
                    ]
                )->with('userInfo')->andFilterWhere($condition)->asArray()->one();

                $cache->set($key,$data,(3600*24*30+rand(1,600)),new TagDependency([
                    'tags'=>UserInfo::CACHE_TAG,
                ]));
                return $data;
            }
        }
    }
}