<?php
namespace frontend\models;

use common\components\helper\SignHelper;
use common\models\startdata\UrlCheck;
use common\models\user\User;
use lbmzorx\components\helper\ModelHelper;
use yii\base\Exception;
use yii\base\Model;
use Yii;
use yii\helpers\VarDumper;

/**
 * Signup form
 */
class ActiveAccount extends Model
{
    public $date;
    public $expire;
    public $sign;
    public $type;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['date','expire','sign','type'],'required'],
            ['date', 'datetime'],
            ['expire', 'integer'],
            ['sign','string','max'=>100],
            ['type','string','max'=>50],
            ['sign', 'exist', 'targetClass' =>'\common\models\startdata\UrlCheck','targetAttribute'=>'md5', 'message' =>\yii::t('app','The activated link is not\'t exist')],
            ['sign','verifySign',],
        ];
    }

    public function attributeLabels()
    {
        return [
            'date'=>\yii::t('app','Date'),
            'expire'=>\yii::t('app','Expire'),
            'sign'=>\yii::t('app','Sign'),
            'type'=>\yii::t('app','Type'),
        ]; // TODO: Change the autogenerated stub
    }

    public function verifySign($attribute){
        $urlCheck=UrlCheck::findOne(['md5'=>$this->sign,'status'=>UrlCheck::STATUS_WAITING]);

        if($urlCheck){
            $checkSign=SignHelper::hiddenSignUrl(['date'=>$this->date,'type'=>'user-signup','expire'=>$urlCheck->expire_time],$urlCheck->auth_key,true,true);
            if($urlCheck->expire_time<time()){
                $urlCheck->status=UrlCheck::STATUS_USELESS;
                $urlCheck->save();
                $this->addError('expire',\yii::t('app','This url was expired!'));
                return false;
            }
            if($checkSign!=false && $checkSign['sign']==$this->sign){
                $db=User::getDb();
                $user=User::findOne(['id'=>$urlCheck->user_id]);
                if($user){
                    $t=$db->beginTransaction();
                    $user->status=User::STATUS_ACTIVE;
                    $urlCheck->num=1;
                    $urlCheck->status=UrlCheck::STATUS_CLICKED;
                    if($user->save()&&$urlCheck->save()){
                        $t->commit();
                        \yii::$app->session->setFlash('info',\yii::t('app','Activated Success,now you can login !'));
                        return true;
                    }else{
                        $t->rollBack();
                        $this->addError('sign',ModelHelper::getErrorAsString($user->getErrors()).ModelHelper::getErrorAsString($urlCheck->getErrors()));
                    }
                    return false;
                }
            }
            $this->addError('sign',\yii::t('app','This url was invalid!'));
        }
        $this->addError('sign',\yii::t('app','This url was invalid!'));
        return false;
    }
}
