<?php
/**
 * Created by Administrator.
 * Date: 2018/6/10 23:55
 * github: https://github.com/lbmzorx
 */

namespace frontend\models;


use yii\base\Model;

class SearchForm extends Model
{
    public $search;

    public function rules()
    {
        return [
            ['search','string','max'=>'50'],
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'search'=>\yii::t('app','Search'),
        ]; // TODO: Change the autogenerated stub
    }

}