<?php
namespace frontend\models;

use yii\base\Model;
use common\models\user\User;

/**
 * Signup form
 */
class SignupForm extends Model
{
    public $username;
    public $email;
    public $password;
    public $confirm_password;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['username', 'trim'],
            ['username', 'required'],
            ['username', 'unique', 'targetClass' => '\common\models\user\User', 'message' => 'This username has already been taken.'],
            ['username', 'string', 'min' => 2, 'max' => 50],

            ['email', 'trim'],
            ['email', 'required'],
            ['email', 'email'],
            ['email', 'string', 'max' => 255],
            ['email', 'unique', 'targetClass' => '\common\models\user\User', 'message' => 'This email address has already been taken.'],

            [['password','confirm_password'], 'required'],
            [['password','confirm_password'], 'string', 'min' => 8,'max'=>25],
            [ 'password','match','pattern'=>'/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)\W{8,25}$/','message'=>\yii::t('app','Password must include number,lowercase letters,and uppercase letters')],
            ['password','compare','compareAttribute'=>'password','operator'=>'===',],
        ];
    }

    /**
     * Signs user up.
     *
     * @return User|null the saved model or null if saving fails
     */
    public function signup()
    {
        if (!$this->validate()) {
            return null;
        }
        
        $user = new User();
        $user->username = $this->username;
        $user->email = $this->email;
        $user->setPassword($this->password);
        $user->generateAuthKey();
        
        return $user->save() ? $user : null;
    }

    public function attributeLabels()
    {
        return [
            'username'=>\yii::t('app','Username'),
            'email'=>\yii::t('app','Email'),
            'password'=>\yii::t('app','Password'),
            'confirm_password'=>\yii::t('app','Confirm Password'),
        ]; // TODO: Change the autogenerated stub
    }
}
