<?php
namespace common\models\admindata;

use Yii;
use common\models\admindatabase\AuthRule as BaseModelAuthRule;
use yii\caching\TagDependency;

/**
* This is the data class for [[common\models\admindatabase\AuthRule]].
* Data model definde model behavior and status code.
* @see \common\models\admindatabase\AuthRule
*/
class AuthRule extends BaseModelAuthRule
{
    /**
     * The cache tag
     */
    const CACHE_TAG='common_models_admindata_AuthRule';


    /**
     * get status code attribute list
     */
    public static function statusCodes(){
        return [
        ];
    }

    /**
    * @inheritdoc
    */
    public function rules()
    {
        return array_merge(parent::rules(),[
        ]);
    }

    /**
    * @inheritdoc
    */
    public function scenarios()
    {
        return [
            'default' => [
                'name',
                'data',
                'created_at',
                'updated_at',
            ],
            'search' => [
                'name',
                'data',
                'created_at',
                'updated_at',
            ],
            'view' => [
                'name',
                'data',
                'created_at',
                'updated_at',
            ],
            'update' => [
                'name',
                'data',
            ],
            'create' => [
                'name',
                'data',
            ],
        ];
    }

    public function behaviors()
    {
        return [
            'timeUpdate'=>[
                'class' => \yii\behaviors\TimestampBehavior::className(),
                'attributes' => [
                    self::EVENT_BEFORE_INSERT => ['created_at'],
                    self::EVENT_BEFORE_UPDATE => ['updated_at'],
                ],
            ],
        ];
    }

    /**
     * If is tree which have parent_id
     * @return boolean
     */
    public static function isTree(){
        return false;
    }


    public function afterSave($insert , $changedAttributes)
    {
        TagDependency::invalidate(\yii::$app->cache,self::CACHE_TAG);
        parent::afterSave($insert , $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        TagDependency::invalidate(\yii::$app->cache,self::CACHE_TAG);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

}
