<?php
namespace common\models\admindata;

use Yii;
use common\models\admindatabase\AuthItemChild as BaseModelAuthItemChild;
use yii\caching\TagDependency;

/**
* This is the data class for [[common\models\admindatabase\AuthItemChild]].
* Data model definde model behavior and status code.
* @see \common\models\admindatabase\AuthItemChild
*/
class AuthItemChild extends BaseModelAuthItemChild
{
    /**
     * The cache tag
     */
    const CACHE_TAG='common_models_admindata_AuthItemChild';


    /**
     * get status code attribute list
     */
    public static function statusCodes(){
        return [
        ];
    }

    /**
    * @inheritdoc
    */
    public function rules()
    {
        return array_merge(parent::rules(),[
        ]);
    }

    /**
    * @inheritdoc
    */
    public function scenarios()
    {
        return [
            'default' => [
                'parent',
                'child',
            ],
            'search' => [
                'parent',
                'child',
            ],
            'view' => [
                'parent',
                'child',
            ],
            'update' => [
                'parent',
                'child',
            ],
            'create' => [
                'parent',
                'child',
            ],
        ];
    }


    /**
     * If is tree which have parent_id
     * @return boolean
     */
    public static function isTree(){
        return false;
    }


    public function afterSave($insert , $changedAttributes)
    {
        TagDependency::invalidate(\yii::$app->cache,self::CACHE_TAG);
        parent::afterSave($insert , $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        TagDependency::invalidate(\yii::$app->cache,self::CACHE_TAG);
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

}
