<?php
/**
 * Created by Administrator.
 * Date: 2018/6/3 15:21
 * github: https://github.com/lbmzorx
 */

namespace common\components\behavior;

use common\components\event\EmailEvent;
use common\models\user\User;
use lbmzorx\components\event\LoginEvent;
use yii\base\Behavior;
class ActivateAccount extends behavior
{
    public $username;

    public function events()
    {
        return [
            EmailEvent::EVENT_BEFORE_EMAIL=>'beforeActivate',
            LoginEvent::EVENT_BEFORE_LOGIN=>'beforeActivate',
        ]; // TODO: Change the autogenerated stub
    }

    public function beforeActivate($event){
        if(preg_match('/^1[\d]{10}$/',$this->username)){
            $user = User::findOne([
                'status' => User::STATUS_WAITING_ACTIVE,
                'mobile' => $this->username,
            ]);
        }elseif(preg_match('/^[^@]*<[a-zA-Z0-9!#$%&\'*+\\/=?^_`{|}~-]+(?:\.[a-zA-Z0-9!#$%&\'*+\\/=?^_`{|}~-]+)*@(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?>$/',$this->username)){
            $user = User::findOne([
                'status' =>User::STATUS_WAITING_ACTIVE,
                'email' => $this->username,
            ]);
        }else{
            $user = User::findOne([
                'status' =>User::STATUS_WAITING_ACTIVE,
                'username' => $this->username,
            ]);
        }

        /* @var $user User */
        if (!$user) {
            return true;
        }

        if ($user->status==User::STATUS_WAITING_ACTIVE) {
            \yii::$app->session->addFlash('info',\yii::t('app','You need activate you account first!'));
            \Yii::$app->response->redirect('/site/activate');
            return false;
        }
    }

}