<?php
/**
 * Created by Administrator.
 * Date: 2018/6/20 20:01
 * github: https://github.com/lbmzorx
 */
namespace common\components\behavior;


use common\components\event\AduitEvent;
use common\models\startdata\Tag;
use common\models\startdata\Article;
use yii\base\Behavior;
use yii\base\Exception;

class ArticleTag extends Behavior
{
    public function events()
    {
        return [
            AduitEvent::EVENT_ADUIT_SUCCESS=>"aduitPass",
            Article::EVENT_AFTER_UPDATE=>"updateTags",
            Article::EVENT_AFTER_DELETE=>"deleteTags",
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * @param $event \yii\db\AfterSaveEvent
     * @throws Exception
     */
    public function updateTags($event){
        /**
         * @var $model Article
         */
        $model=$event->sender;
        if(array_key_exists('tag',$event->changedAttributes)){
            $newTag=$model->getAttribute('tag');
            $oldTag=$event->changedAttributes['tag'];
            if($newTag!=$oldTag){
                $this->subTagFrequence($oldTag);
            }
        }
    }

    public function aduitPass($event){
        /**
         * @var $model Article
         */
        $model=$event->sender;
        $this->increTagFrequence($model->tag);
    }

    public function deleteTags($event){
        /**
         * @var $model Article
         */
        $model=$event->sender;
        $this->subTagFrequence($model->tag);
    }

    protected function increTagFrequence($tag){
        $tag=Tag::findOne(['name'=>$tag]);
        if($tag){
            $tag->updateCounters(['frequence'=>1]);
        }else{
            $tag=new Tag();
            $tag->name=$tag;
            $tag->frequence=1;
            $tag->save();
        }
    }

    protected function subTagFrequence($tag){
        $tag=Tag::findOne(['name'=>$tag]);
        if($tag){
            if($tag->frequence==1){
                $tag->delete();
            }else{
                $tag->updateCounters(['frequence'=>-1]);
            }
        }
    }

}