<?php
/**
 * Created by Administrator.
 * Date: 2018/6/20 20:01
 * github: https://github.com/lbmzorx
 */
namespace common\components\behavior;


use common\components\event\AduitEvent;
use common\models\startdata\Tag;
use common\models\startdata\Article;
use lbmzorx\components\helper\ModelHelper;
use yii\base\Behavior;
use yii\base\Exception;
use yii\helpers\VarDumper;
use yii\log\Logger;

class ArticleTag extends Behavior
{
    public function events()
    {
        return [
            AduitEvent::EVENT_ADUIT_SUCCESS=>"aduitPass",
            Article::EVENT_AFTER_UPDATE=>"updateTags",
            Article::EVENT_AFTER_DELETE=>"deleteTags",
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * @param $event \yii\db\AfterSaveEvent
     * @throws Exception
     */
    public function updateTags($event){
        /**
         * @var $model Article
         */
        $model=$event->sender;
        if(array_key_exists('tag',$event->changedAttributes)){
            $newTag=$model->getAttribute('tag');
            $oldTag=$event->changedAttributes['tag'];
            if($newTag!=$oldTag){
                $this->subTagFrequence($oldTag);
                if($model->status==Article::STATUS_AUDIT_PASSED){
                    $this->increTagFrequence($newTag);
                }
            }
        }
    }

    public function aduitPass($event){
        /**
         * @var $model Article
         */
        $model=$event->sender;
        $this->increTagFrequence($model->tag);
    }

    public function deleteTags($event){
        /**
         * @var $model Article
         */
        $model=$event->sender;
        $this->subTagFrequence($model->tag);
    }

    protected function increTagFrequence($tag){

        $tag=str_replace([' ','，'],',',$tag);
        $tags=array_filter(explode(',',$tag));
        $tagModels=Tag::find()->where(['name'=>$tags])->indexBy('name')->all();
        $newTags=array_diff($tags,array_keys($tagModels));

        foreach ($tagModels as $v){
            $v->updateCounters(['frequence'=>1]);
        }
        foreach ($newTags as $v){
            $tag=new Tag();
            $tag->name=$v;
            $tag->frequence=1;
            if(!$tag->save()){
                \yii::$app->log->logger->log(ModelHelper::getErrorToString($tag),Logger::LEVEL_INFO,"tag_save_failed");
            }
        }
    }

    protected function subTagFrequence($tag){

        $tag=str_replace([' ','，'],',',$tag);
        $tags=explode(',',$tag);
        $tagModels=Tag::find()->where(['name'=>$tags])->all();
        foreach ($tagModels as $model){
            if($model->frequence==1){
                $model->delete();
            }else{
                $model->updateCounters(['frequence'=>-1]);
            }
        }
    }

}