<?php
/**
 * Created by Administrator.
 * Date: 2018/6/8 21:41
 * github: https://github.com/lbmzorx
 */
namespace common\components\behavior;


use common\components\event\MqEvent;
use yii\base\Behavior;
class MqQueue extends Behavior
{
    public function events()
    {
        return [
            MqEvent::EVENT_BEFORE_SEND=>'beforeSend',
            MqEvent::EVENT_AFTER_SEND=>'afterSend',
        ]; // TODO: Change the autogenerated stub
    }

    public function beforeSend($event){

    }

    public function afterSend($event){

    }
}