<?php
/**
 * Created by Administrator.
 * Date: 2018/7/7 17:54
 * github: https://github.com/lbmzorx
 */

namespace chat\modules\v1\components;


use lbmzorx\components\helper\ModelHelper;
use yii\base\ActionEvent;
use yii\base\Behavior;
use yii\base\Model;
use yii\rest\Controller;


/**
 * @SWG\Definition(
 *     type="object",
 *     definition="Common-response",
 *     @SWG\Xml(name="公共响应格式")
 * )
 */
class ApiResponseBehavior extends Behavior
{
    public function events()
    {
        return array_merge(parent::events(),[
            Controller::EVENT_AFTER_ACTION=>'formatCode',
        ]); // TODO: Change the autogenerated stub
    }


    /**
     * @SWG\Property(
     *     title="状态码",
     *     property="status_code",
     *     type="int32",
     *     description="响应码",
     *     example="200",
     * ),
     * @SWG\Property(
     *     title="响应信息",
     *     property="message",
     *     type="string",
     *     description="响应信息",
     *     example="例如success",
     * ),
     *@SWG\Property(
     *     title="响应结果",
     *     property="result",
     *     type="string",
     *     description="响应结果",
     *     example={"title":"test"},
     *     @SWG\Property(
     *          example="Alan Jones",
     *          property="data",
     *     )
     * )
     */

    /**
     * @param $event ActionEvent
     */
    public function formatCode($event){
        $result=$event->result;
        $res=[
            'status_code'=>200,
            'message'=>'Success',
            'result'=>[],
        ];
        if($result instanceof Model){
            if($result->hasErrors()){
                $res=[
                    'status_code'=>400,
                    'message'=>ModelHelper::getErrorToString($result),
                    'result'=>[],
                ];
            }
        }
        if(isset($result['status_code'])){
            $res['status_code']=$result['status_code'];
            unset($result['status_code']);
        }
        if(isset($result['message'])){
            $res['message']=$result['message'];
            unset($result['message']);
        }
        $res['result']=$result;
        $event->result=$res;
    }

}